
mqtt:
  address: "192.168.1.206"
  port: 1883
  qos: 2 # remember to set

  mainTopic: modbus-to-mqtt

modbus:
  address: "192.168.1.12"
  port: 502

  readAddresses:
  - type: coil
    start: 0
    count: 32

  scanInterval: 80
  longPressTime: 1000