
mqtt:
  address: "192.168.1.206"
  port: 1883
  qos: 2

  mainTopic: modbus-to-mqtt

modbus:
  address: "192.168.1.12"
  port: 502

  blocks:
  - type: coil
    start: 0
    count: 1
    topic: 'di/{{.Address}}'
    
    report: 
    - sendOn: '{{and (gt .State.LastChanged 999) (not .State.Value)}}'
      format: long
      onlyOnChange: true
    - sendOn: '{{and (lt .State.LastChanged 1000) (not .State.Value)}}'
      format: short
      onlyOnChange: true
  scanInterval: 80

metrics:
  enabled: true
