
mqtt:
  address: "192.168.1.206"
  port: 1883
  qos: 2

  mainTopic: modbus-to-mqtt

modbus:
  address: "192.168.1.12"
  port: 502

  addresses:
  - type: coil
    start: 0
    count: 32
    topic: 'output'
    reportFormat: '{"address": {{.Address}}, "on": {{.Value}}}'

  scanInterval: 80
  longPressTime: 1000

metrics:
  enabled: true
