
mqtt:
  address: "192.168.1.206"
  port: 1883
  qos: 2

  mainTopic: modbus-to-mqtt

modbus:
  address: "192.168.1.12"
  port: 502

  addresses:
  - type: coil
    start: 0
    count: 32
    topic: 'output'
    report: 
    - enabled: '{{and (gt .LastChanged 999) (not .Value) .Changed }}'
      format: '{"address": {{.Address}}, "press": "long"}'
    - enabled: '{{and (lt .LastChanged 1000) (not .Value) .Changed }}'
      format: '{"address": {{.Address}}, "press": "short"}'

  scanInterval: 80

metrics:
  enabled: true
